name: dognal1
description: "dognal1"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^6.0.0
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  msgpack_dart: ^1.0.1
  supabase_flutter: ^2.5.0
  geolocator: ^12.0.0
  flutter_riverpod: ^2.5.0
  riverpod_annotation: ^2.3.5
  rive: ^0.13.0
  google_maps_flutter: ^2.6.1       # 구글 지도
  location: ^6.0.2                  # GPS 위치 정보
  weather: ^3.1.1                   # 날씨 정보
  image_picker: ^1.1.2              # 사진 촬영/선택
  geocoding: ^3.0.0                 # 좌표-주소 변환
  google_maps_flutter_web: ^0.5.5


  # ✨ [추가] 그래프 및 날짜/시간 처리를 위한 라이브러리
  fl_chart: ^0.68.0
  intl: ^0.19.0

  # ✨ [추가] 마크다운 렌더링을 위한 라이브러리
  flutter_markdown: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  riverpod_generator: ^2.3.5
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # ✨ [복원] assets/ 폴더 대신 원래대로 루트의 .env 파일을 지정합니다.
  assets:
    - .env
